[build-system]
requires = ["setuptools>=61.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pcassie"
dynamic = ["version"]

[tool.setuptools_scm]
write_to = "pcassie/_version.py"
